{
 "title": "IoT data Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Location 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TempSens_1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": " SELECT\r\n  UNIX_TIMESTAMP(Measurements_TimeStamp) as time_sec,\r\n  senValue as value,\r\n  Sensors_idSensors as metric\r\nFROM logger\r\nWHERE $__timeFilter(Measurements_TimeStamp) AND Sensors_idSensors='TempSens_1'\r\nORDER BY Measurements_TimeStamp ASC"
    }
   ]
  },
  {
   "title": "HumSens_1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": " SELECT\r\n  UNIX_TIMESTAMP(Measurements_TimeStamp) as time_sec,\r\n  senValue as value,\r\n  Sensors_idSensors as metric\r\nFROM logger\r\nWHERE $__timeFilter(Measurements_TimeStamp) AND Sensors_idSensors='HumSens_1'\r\nORDER BY Measurements_TimeStamp ASC"
    }
   ]
  },
  {
   "title": "TempSens_1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT\r\n  UNIX_TIMESTAMP(Measurements_TimeStamp) as time_sec,\r\n  senValue as value,\r\n  Sensors_idSensors as metric\r\nFROM logger\r\nWHERE $__timeFilter(Measurements_TimeStamp) AND Sensors_idSensors='TempSens_1'\r\nORDER BY Measurements_TimeStamp ASC"
    }
   ]
  },
  {
   "title": "HumSens_1",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT\r\n  UNIX_TIMESTAMP(Measurements_TimeStamp) as time_sec,\r\n  senValue as value,\r\n  Sensors_idSensors as metric\r\nFROM logger\r\nWHERE $__timeFilter(Measurements_TimeStamp) AND Sensors_idSensors='HumSens_1'\r\nORDER BY Measurements_TimeStamp ASC"
    }
   ]
  },
  {
   "title": "VoltSens_1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": " SELECT\r\n  UNIX_TIMESTAMP(Measurements_TimeStamp) as time_sec,\r\n  senValue as value,\r\n  Sensors_idSensors as metric\r\nFROM logger\r\nWHERE $__timeFilter(Measurements_TimeStamp) AND Sensors_idSensors='VoltSens_1'\r\nORDER BY Measurements_TimeStamp ASC"
    }
   ]
  },
  {
   "title": "CurSens_1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": " SELECT\r\n  UNIX_TIMESTAMP(Measurements_TimeStamp) as time_sec,\r\n  senValue as value,\r\n  Sensors_idSensors as metric\r\nFROM logger\r\nWHERE $__timeFilter(Measurements_TimeStamp) AND Sensors_idSensors='CurSens_1'\r\nORDER BY Measurements_TimeStamp ASC"
    }
   ]
  },
  {
   "title": "VoltSens_1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT\r\n  UNIX_TIMESTAMP(Measurements_TimeStamp) as time_sec,\r\n  senValue as value,\r\n  Sensors_idSensors as metric\r\nFROM logger\r\nWHERE $__timeFilter(Measurements_TimeStamp) AND Sensors_idSensors='VoltSens_1'\r\nORDER BY Measurements_TimeStamp ASC"
    }
   ]
  },
  {
   "title": "CurSens_1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT\r\n  UNIX_TIMESTAMP(Measurements_TimeStamp) as time_sec,\r\n  senValue as value,\r\n  Sensors_idSensors as metric\r\nFROM logger\r\nWHERE $__timeFilter(Measurements_TimeStamp) AND Sensors_idSensors='CurSens_1'\r\nORDER BY Measurements_TimeStamp ASC"
    }
   ]
  },
  {
   "title": "powFact_1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " SELECT\r\n  UNIX_TIMESTAMP(Measurements_TimeStamp) as time_sec,\r\n  senValue as value,\r\n  Sensors_idSensors as metric\r\nFROM logger\r\nWHERE $__timeFilter(Measurements_TimeStamp) AND Sensors_idSensors='powFactSens_1'\r\nORDER BY Measurements_TimeStamp ASC"
    }
   ]
  },
  {
   "title": "powFact_1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": " SELECT\r\n  UNIX_TIMESTAMP(Measurements_TimeStamp) as time_sec,\r\n  senValue as value,\r\n  Sensors_idSensors as metric\r\nFROM logger\r\nWHERE $__timeFilter(Measurements_TimeStamp) AND Sensors_idSensors='powFactSens_1'\r\nORDER BY Measurements_TimeStamp ASC"
    }
   ]
  }
 ]
}